USE [master]
GO

/****** Object:  Database [backpack]    Script Date: 20.03.2026 8:50:27 ******/
DROP DATABASE [backpack]
GO

/****** Object:  Database [backpack]    Script Date: 20.03.2026 8:50:27 ******/
CREATE DATABASE [backpack]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'backpack', FILENAME = N'D:\Database\backpack.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'backpack_log', FILENAME = N'D:\Database\backpack_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [backpack].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [backpack] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [backpack] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [backpack] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [backpack] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [backpack] SET ARITHABORT OFF 
GO

ALTER DATABASE [backpack] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [backpack] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [backpack] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [backpack] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [backpack] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [backpack] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [backpack] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [backpack] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [backpack] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [backpack] SET  DISABLE_BROKER 
GO

ALTER DATABASE [backpack] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [backpack] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [backpack] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [backpack] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [backpack] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [backpack] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [backpack] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [backpack] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [backpack] SET  MULTI_USER 
GO

ALTER DATABASE [backpack] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [backpack] SET DB_CHAINING OFF 
GO

ALTER DATABASE [backpack] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [backpack] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [backpack] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [backpack] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [backpack] SET QUERY_STORE = ON
GO

ALTER DATABASE [backpack] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [backpack] SET  READ_WRITE 
GO

